# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180710_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='rcount',
            field=models.IntegerField(default=0),
        ),
    ]
