# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_rcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('comms', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'use_comments',
            },
        ),
        migrations.AlterField(
            model_name='blogs',
            name='marks',
            field=models.ForeignKey(default='\u672a\u5206\u7c7b', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='blog_marks', to='blog.Bmarks', to_field='tags'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='uname',
            field=models.ForeignKey(default='\u533f\u540d', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='auth_user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='comments',
            name='blogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_blogs', to='blog.Blogs', to_field='title'),
        ),
    ]
