# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180711_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='uses',
            field=models.CharField(default='\u533f\u540d', max_length=128),
        ),
    ]
