# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blogs',
            field=models.ForeignKey(default='\u8be5\u535a\u5ba2\u5df2\u5220\u9664', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_blogs', to='blog.Blogs', to_field='title'),
        ),
    ]
