# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180711_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='blogs',
            new_name='cblog',
        ),
    ]
