# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180711_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cblog',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
