# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180711_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cbid',
            field=models.IntegerField(null=True),
        ),
    ]
