# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments_cbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
