# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comments_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, max_length=30, null=True),
        ),
    ]
