# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180711_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='coms',
            field=models.IntegerField(default=0),
        ),
    ]
