# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=256)),
                ('ctime', models.DateTimeField(auto_now_add=True, max_length=30)),
                ('utime', models.DateTimeField(auto_now=True, max_length=30)),
            ],
            options={
                'db_table': 'user_blogs',
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2',
            },
        ),
        migrations.CreateModel(
            name='Bmarks',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'blog_marks',
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='\u7537', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-c_time'],
                'verbose_name_plural': '\u7528\u6237',
                'db_table': 'login_user',
                'verbose_name': '\u7528\u6237',
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='bmarks',
            unique_together=set([('tags',)]),
        ),
        migrations.AddField(
            model_name='blogs',
            name='marks',
            field=models.ForeignKey(default='\u672a\u5206\u7c7b', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_marks', to='login.Bmarks', to_field='tags'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='uname',
            field=models.ForeignKey(default='\u533f\u540d', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_user', to='login.User', to_field='name'),
        ),
        migrations.AlterUniqueTogether(
            name='blogs',
            unique_together=set([('title',)]),
        ),
    ]
