# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bmarks',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'blog_marks',
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bmarks',
            unique_together=set([('tags',)]),
        ),
        migrations.AddField(
            model_name='blogs',
            name='marks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_marks', to='login.Bmarks', to_field='tags'),
        ),
    ]
