# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopp',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='c666', max_length=20, verbose_name='\u8bf7\u8f93\u5165\u540d\u5b57')),
                ('phone', models.CharField(max_length=11, null=True)),
                ('sex', models.CharField(default='3', max_length=2, null=True)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.EmailField(default='a@b.com', max_length=20, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True, max_length=30)),
            ],
        ),
    ]
