# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20180629_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopp',
            name='utime',
            field=models.DateTimeField(auto_now=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='shopp',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, max_length=30),
        ),
    ]
