# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20180629_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopp',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopp',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u8bf7\u8f93\u5165\u540d\u5b57'),
        ),
    ]
