# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20180629_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopp',
            name='sex',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
