# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('period', models.IntegerField(db_index=True, verbose_name='\u8bfe\u7a0b\u5b66\u65f6')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='\u6559\u5e08\u540d\u5b57')),
                ('gender', models.IntegerField(verbose_name='\u6559\u5e08\u6027\u522b')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='\u6559\u5e08\u4f4f\u5740')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='ctable.Course')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('title',)]),
        ),
    ]
