# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('title',)]),
        ),
    ]
