# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
