# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_moment_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java'), ('script', 'script'), ('android', 'android'), ('else', 'else')], max_length=20),
        ),
    ]
