# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180701_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('python', 'python'), ('java', 'java'), ('script', 'script'), ('android', 'android'), ('else', 'else')], max_length=20, verbose_name='\u6587\u7ae0\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='moment',
            name='title',
            field=models.CharField(max_length=20, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
    ]
