# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
