# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='cz666', max_length=30)),
                ('phone', models.IntegerField(default='88888888888')),
                ('sex', models.CharField(default='3', max_length=10)),
                ('email', models.EmailField(default='a@b.com', max_length=20, null=True)),
                ('createtimes', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
